### ISSUE TITLE
Metadata Issue with Unofficial Patch Plus and JSawyer Ultimate in Fallout New Vegas

### ISSUE THREAD

**Issue by MoerasGrizzly** [loot/falloutnv#101]
Unofficial Patch Plus is a patch mod that's supposed to be loaded after YUP and before most other mods.

JSawyer Ultimate Edition is a mod by the same author who made UPP. It incorperates UPP fixes, and it should be loaded after UPP.

**Comment by pStyl3** [comment]
[Unofficial Patch Plus](https://www.nexusmods.com/newvegas/mods/62953)
[JSawyer Ultimate Edition](https://www.nexusmods.com/newvegas/mods/61592)

LOOT's current masterlist contains the following:
```yaml
  - name: 'Unofficial Patch Plus.esp'
    url: ['https://www.nexusmods.com/newvegas/mods/62953']
    inc: [ *TTWv320 ]
```
And:
```yaml
  - name: 'JSawyer Ultimate.esp'
    url: [ 'https://www.nexusmods.com/newvegas/mods/61592' ]
    tag:
      - Delev
      - Factions
      - Invent
      - Names
      - Relev
```
