### ISSUE TITLE
Remove &updateToNVCE

### ISSUE THREAD

**Issue by pStyl3** [loot/falloutnv#116]
```yaml
  - &updateToNVCE
    type: say
    content: '"Old, update to [NVCE](https://www.nexusmods.com/newvegas/mods/39325)."'
```
This message is only used by these three plugins:

```yaml
  - name: 'Machienzo - NPC Cosmetic Fixes - Ver 1.55.esm'
    msg: [ *updateToNVCE ]
    tag:
      - Body-F
      - Body-M
      - Eyes
      - Hair
      - NpcFaces
      - R.Mouth
      - R.Teeth
      - Voice-F
      - Voice-M
  - name: 'Machienzo - NPC Cosmetic Fixes - Ver 1.57.esm'
    msg: [ *updateToNVCE ]
    tag:
      - Body-F
      - Body-M
      - Eyes
      - Hair
      - NpcFaces
      - R.Mouth
      - R.Teeth
      - Voice-F
      - Voice-M
  - name: 'Machienzo - NPC Cosmetic Fixes.esm'
    msg: [ *updateToNVCE ]
    tag:
      - Body-F
      - Body-M
      - Eyes
      - Hair
      - NpcFaces
      - R.Mouth
      - R.Teeth
      - Voice-F
      - Voice-M
```
I cannot find the plugins on Nexus (or anywhere else), though a google search suggests, that those plugins were created over [10 years ago](https://forums.guru3d.com/threads/fallout-new-vegas.314813/page-79).

As such, removing the plugins and `&updateToNVCE` is favourable.
