### ISSUE TITLE
Reevaluate &updateToYUP

### ISSUE THREAD

**Issue by pStyl3** [loot/falloutnv#117]
```yaml
  - &updateToYUP
    type: say
    content: 'Outdated. Consider using the latest version of [Yukichigai Unofficial Patch - YUP](https://www.nexusmods.com/newvegas/mods/51664) instead.'
```
This message is currently used for 15 plugins:
```
Community Bugfix Compilation Patch.esm
OFT_Merge_All.esm
OFT_Merge_Base.esm
OFT_Merge_HonestHearts.esm
OFT_Merge_OldWorldBlues.esm
MM-Main.esp
MM-HonestHearts.esp
MM-OldWorldBlues.esp
MM-LonesomeRoad.esp
Mission Mojave - Ultimate Edition.esp
MMUE+.esp
Mission Mojave - Ultimate Edition Plus.esp
Mission Mojave - Ultimate Edition Plus Standalone.esp
Community Bugfix Compilation Patch.esp
Compiled Patch All_DLCs.esp
```
Consider refactoring `&updateToYUP` to use an already localized Message, maybe `&useInstead`.

```yaml
  - &useInstead
    type: warn
    content:
      - lang: en
        text: 'Use %1% instead.'
      - lang: de
        text: 'Nutzen Sie %1% stattdessen.'
      - lang: ja
        text: '代わりに%1%を使用してください。'
      - lang: sv
        text: 'Använd %1% istället.'
```
