### ISSUE TITLE
Some more ITMs

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/falloutnv#222]
[Vanessa Follower](https://www.nexusmods.com/newvegas/mods/56270)
```
  - name: 'VanessaFollowerNV.esm'
    dirty:
      - <<: *quickClean
        crc: 0x0AD51D00
        util: '[FNVEdit v4.0.3](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 80
    clean:
      - crc: 0xA41844B6
        util: 'FNVEdit v4.0.3'
```
[Cut Sewers Restored](https://www.nexusmods.com/newvegas/mods/55956)
```
  - name: 'Cut Sewers Restored.esp'
    dirty:
      - <<: *quickClean
        crc: 0x62FBFB05
        util: '[FNVEdit v4.0.3](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 1
    clean:
      - crc: 0x8674DAB0
        util: 'FNVEdit v4.0.3'
```
[Metal Boxes](https://www.nexusmods.com/newvegas/mods/63422)
```
  - name: 'MetalBoxes.esp'
    dirty:
      - <<: *quickClean
        crc: 0x40F41790
        util: '[FNVEdit v4.0.3](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 1
    clean:
      - crc: 0x3F3B9519
        util: 'FNVEdit v4.0.3'
```
[ARES Project](https://www.nexusmods.com/newvegas/mods/48621)
```
  - name: 'ARESproject.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0xBC0620B7
        util: '[FNVEdit v4.0.3](https://www.nexusmods.com/newvegas/mods/34703)'
        nav: 5
```
