### ISSUE TITLE
Add ESP containing Navmesh warning/error messages

### ISSUE THREAD

**Issue by Superfly-Johnson** [loot/falloutnv#351]
In Fallout 3 and New Vegas, esps containing navmeshes can cause save bloating, crashes, general game instability and generally odd pathing/AI bugs. 

I think a message is in order.

**Comment by pStyl3** [comment]
Can you provide examples for both FO3 and FNV?

**Comment by Superfly-Johnson** [comment]
According to inthegrave (modder behind the navmesh overhaul mod) and roybatty a notorious example is all NPCs spawning in a particular plugin's additional navmeshes. 

CarlZee of Raiders behind the capital wasteland also cited a similar example on discord.

**Comment by pStyl3** [comment]
Can you point me to where those people made those statements?
Are there specific plugins that have been identified to cause the above described issues?

**Comment by Superfly-Johnson** [comment]
![SmartSelect_20231001_200449_Discord](https://github.com/loot/falloutnv/assets/68615650/ee46c529-2b06-4434-ac56-a0265ca8434e)
Sorry for the weird crop, I'm not home ATM.

Basically ESP navmesh islands can cause things like pathfinding totally breaking and NPCs spawning on top of building. I'd like to get a video of pathfinding breaking.

According to inthegrave the same issues don't happen when the same plugin is flagged as ESM

**Comment by Superfly-Johnson** [comment]
[NavmeshOverhaulTEST.zip](https://github.com/loot/falloutnv/files/12778718/NavmeshOverhaulTEST.zip)
Try this plugin, coc 0010BEEE, unlock the Strip North Gate, go in, go to the tops, come back, if it still hasn't happened go from the inside hte omertas to the lower brimstones, come out. You'll see it. 

https://www.youtube.com/watch?v=COrndOGiJLw&feature=youtu.be (NavmeshOverhaulTEST.esp, before flagging as ESM)

https://www.youtube.com/watch?v=ut83dGqsR8c&feature=youtu.be (NavmeshOverhaulTEST.esp, after flagging as ESM)

As you can see no more NPCs spawning on rooftops. I also noticed AI totally stopping working until they were hit. I think a message is more than warranted, especially for budding mod authors

**Comment by Superfly-Johnson** [comment]
I'd like an update on it, I'm currently working on adding a mod where I would like a "Flag as ESM" message as it contains a plugin which itself contains a navmesh.

**Comment by pStyl3** [comment]
After [some discussion](https://discord.com/channels/473542112974077963/473721823071043585/1178403733013545060) on Discord we decided on the following message:

prelude.yaml
```yaml
  # Useful for Fallout 3 and Fallout New Vegas plugins
  - &flagESM
    type: warn
    content:
      - lang: en
        text: 'This plugin isn't an ESM, but it appears to contain navmeshes. This can lead to problems with NPC pathfinding. It is recommended to flag this plugin as **ESM** to avoid these problems. It might also be necessary to ensure that all references called by scripts in this plugin are flagged as **persistent**.'
```

masterlist.yaml
```yaml
  - name: 'Example.esp'
    msg:
      - <<: *flagESM
        condition: 'not is_master("Example.esp")'
```

I'll be implementing the message anchor now.

Discord discussion:

<img width="890" height="1041" alt="Image" src="https://github.com/user-attachments/assets/c942109a-27d8-4027-9dd3-9f48417ee766" />

<img width="890" height="513" alt="Image" src="https://github.com/user-attachments/assets/a8f9b238-379f-4a36-b3de-ce0f0873276a" />

<img width="890" height="1052" alt="Image" src="https://github.com/user-attachments/assets/f26b6dd9-54c4-48b0-a699-8e7c8209cc0f" />

<img width="890" height="550" alt="Image" src="https://github.com/user-attachments/assets/239c50c7-7fb9-4455-ba0a-f3cc69a2b131" />
