### ISSUE TITLE
ENBSeries incompatible to NVTF and NVHR

### ISSUE THREAD

**Issue by pStyl3** [loot/falloutnv#352]
Reference: https://github.com/loot/falloutnv/pull/349

[ENBSeries](http://enbdev.com/mod_falloutnv_v0451.htm)
[New Vegas Tick Fix (NVTF)](https://www.nexusmods.com/newvegas/mods/66537/)
[New Vegas Heap Replacer (NVHR)](https://www.nexusmods.com/newvegas/mods/69779/)

ENBSeries seems to be incompatible with NVTF and NVHR.
Consider adding a message in LOOT that informs the user of them being incompatible.

**Comment by MacSplody** [comment]
We'll need a new message in prelude for incompatible, to use in globals.
Is it possible to use existing localisation used for `inc:`?

**Comment by pStyl3** [comment]
The `inc` message is defined in `game.cpp` [here](https://github.com/loot/loot/blob/master/src/gui/state/game/game.cpp#L472) and it reads:

`This plugin is incompatible with \"{0}\", but both are present.`

As such, the masterlist entry

```yaml
  - name: 'WMIMNV.esp'
    inc:
      - 'EVE FNV - ALL DLC.esp'
```

will result in the following, if both plugins are present:

![grafik](https://github.com/loot/falloutnv/assets/10406657/684000a0-9251-4464-ae5c-02a2e2d85560)

If we wanted to warn about an incompatibility between `WMIMNV.esp` and `ENBSeries`, we could expand the `inc` list of `WMIMNV.esp` like so:

```yaml
  - name: 'WMIMNV.esp'
    inc:
      - name: '../ENBInjector.exe'
        display: 'ENBSeries (InjectorVersion)'
      - name: '../enbhost.exe'
        display: 'ENBSeries (WrapperVersion)'
```

It would result in:

![grafik](https://github.com/loot/falloutnv/assets/10406657/94cddefd-971b-4d5f-ac96-b617cc506300)

___

This issue however is about warning about an incompatibility between
- `ENBSeries` and `New Vegas Tick Fix` (`NVSE/Plugins/NVTF.dll`)
- `ENBSeries` and `New Vegas Heap Replacer` (`NVHR/nvhr_avx.dll`)

where no plugins are involved, so the `inc` message doesn't seem appropriate.

The best course is likely indeed to create a new message in the `prelude` and utilise it in the `masterlist`'s `global` node.

**Comment by pStyl3** [comment]
I would suggest the following:

prelude.yaml
```yaml
  - &incompatible
    type: error
    content:
      - lang: en
        text: '{0} is incompatible with {1}, but both are present.'
    subs:
      - 'non-plugin mod 0'
      - 'non-plugin mod 1'
    condition: 'file("NVSE/Plugins/0.dll") and file("NVSE/Plugins/1.dll")'
```

masterlist.yaml
```yaml
prelude:
  common:
  # Global Anchors

    - &incompatible
      type: error
      content: '{0} is incompatible with {1}, but both are present.'


globals:
# ENBSeries - NVHR
  - <<: *incompatible
    subs:
      - '[ENBSeries](http://enbdev.com/mod_falloutnv_v0451.htm)'
      - '[NVHR - New Vegas Heap Replacer](https://www.nexusmods.com/newvegas/mods/69779/)'
    condition: 'file("NVHR/nvhr_avx.dll") and (file("../ENBInjector.exe") or file("../enbhost.exe"))'


# ENBSeries - NVTF
  - <<: *incompatible
    subs:
      - '[ENBSeries](http://enbdev.com/mod_falloutnv_v0451.htm)'
      - '[NVTF - New Vegas Tick Fix](https://www.nexusmods.com/newvegas/mods/66537/)'
    condition: 'file("NVSE/Plugins/NVTF.dll") and (file("../ENBInjector.exe") or file("../enbhost.exe"))'
```

Result:
![grafik](https://github.com/loot/falloutnv/assets/10406657/3fa7a735-0133-4293-b385-169567eb5610)
