### ISSUE TITLE
YUP must load after NavmeshOverhaul.esm

### ISSUE THREAD

**Issue by MacSplody** [loot/falloutnv#377]
> `NavmeshOverhaul.esm` should also be loaded **before** YUP, according to https://www.nexusmods.com/newvegas/mods/81003?tab=description but I see no way of specifying that?

That can be done by specifying that YUP must load after `NavmeshOverhaul.esm`. So it would probably be the best course of action to expand our following existing entry
```yaml
  - name: 'YUP .*\.es[mp]'
    url:
      - link: 'https://www.nexusmods.com/newvegas/mods/51664/'
        name: 'Yukichigai Unofficial Patch - YUP'
```

by adding a load after to that. So:
```yaml
  - name: 'YUP .*\.es[mp]'
    url:
      - link: 'https://www.nexusmods.com/newvegas/mods/51664/'
        name: 'Yukichigai Unofficial Patch - YUP'
    after: [ 'NavmeshOverhaul.esm' ]
```

_Originally posted by @pStyl3 in https://github.com/loot/falloutnv/issues/370#issuecomment-1949890234_
