### ISSUE TITLE
TTW - Add Do Not Clean to FO3 DLC

### ISSUE THREAD

**Issue by MacSplody** [loot/falloutnv#43]
- [x] `Fallout3.esm`
- [x] `Anchorage.esm`
- [x] `ThePitt.esm`
- [x] `BrokenSteel.esm`
- [x] `PointLookout.esm`
- [x] `Zeta.esm`

**Comment by pStyl3** [comment]
Why should we add the Do Not Clean message to the official plugins? Is it, because of what is described, for example, [here](https://wiki.step-project.com/User:Kelmych/Fallout3#Fix_the_Deleted_Navmeshes_in_the_Bethesda_DLC_ESMs)? So that the mentioned navmesh should be fixed before cleaning the plugins? If yes, how about adding a message "fix the navmesh before cleaning" instead of adding Do Not Clean?

**Comment by MacSplody** [comment]
@pStyl3 TTW installer requires unmodified DLC from both FO3 and FNV.

**Comment by pStyl3** [comment]
The message should then be conditionalized in some way or another. Either show the messages only if some specific TTW plugin is present, or use `do not clean if TTW ..` instead of a generic `do not clean`.

I don't think we should generally leave out the dirty info because of one specific mod

**Comment by MacSplody** [comment]
>I don't think we should generally leave out the dirty info because of one specific mod

I'm running through the installation at the moment. It appears as though all the plugins are modified during TTW setup. If that's the case, no existing cleaning info will need a seperate message.

And I don't think there's any point having a message for before TTW installs. Since the installer will fail if a modified plugin is detected iirc.

So it's just the plugins that the installer creates, that need to be marked as `do not clean`.

> Either show the messages only if some specific TTW plugin in present, or use do not clean if TTW .. instead of a generic do not clean.

A seperate `Do not clean` message for TTW would be best.

**Comment by MacSplody** [comment]
Finally installed, so the installer only modifies the FO3 plugins.
`Fallout3.esm`, `Anchorage.esm`, `ThePitt.esm`, `BrokenSteel.esm`, `PointLookout.esm` and `Zeta.esm`.
It doesn't touch the FNV plugins.

`Fallout3.esm` and `BrokenSteel.esm` have a few ITMs the rest are clean.
I'm not sure if those crc32 are reliable.

```yaml
  - name: 'Fallout3.esm'
    dirty:
      - <<: *quickClean
        crc: 0x25A3A5EA
        util: '[FNVEdit v4.0.2](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 8
    clean:
      - crc: 0xF6D63708
        util: 'FNVEdit v4.0.2'

  - name: 'Anchorage.esm'
    clean:
      - crc: 0x29D83A66
        util: 'FNVEdit v4.0.2'

  - name: 'ThePitt.esm'
    clean:
      - crc: 0x93B1A85B
        util: 'FNVEdit v4.0.2'

  - name: 'BrokenSteel.esm'
    dirty:
      - <<: *quickClean
        crc: 0x2042CB73
        util: '[FNVEdit v4.0.2](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 10
    clean:
      - crc: 0xBA474FBE
        util: 'FNVEdit v4.0.2'

  - name: 'PointLookout.esm'
    clean:
      - crc: 0x918AFC89
        util: 'FNVEdit v4.0.2'

  - name: 'Zeta.esm'
    clean:
      - crc: 0xD161F2DB
        util: 'FNVEdit v4.0.2'
```
