### ISSUE TITLE
Fallout New California must load first after DLCs

### ISSUE THREAD

**Issue by RowanSkie** [loot/falloutnv#47]
https://www.nexusmods.com/newvegas/mods/45138

As told by the team itself, NewCalifornia.esm must be after the DLCs and before anything else.

**Comment by ghost** [comment]
```
  - name: 'NewCalifornia.esm'
    url: [ 'https://www.nexusmods.com/newvegas/mods/45138' ]
    group: *ttwGroup
    after:
      - 'DeadMoney.esm'
      - 'HonestHearts.esm'
      - 'OldWorldBlues.esm'
      - 'LonesomeRoad.esm'
      - 'GunRunnersArsenal.esm'
      - 'CaravanPack.esm'
      - 'ClassicPack.esm'
      - 'MercenaryPack.esm'
      - 'TribalPack.esm'
    inc:
      - 'Fallout3.esm'
      - 'Anchorage.esm'
      - 'ThePitt.esm'
      - 'BrokenSteel.esm'
      - 'PointLookout.esm'
      - 'Zeta.esm'
      - 'TaleOfTwoWastelands.esm'
      - 'Alternative Start.esp'
- 'Mission Mojave - Ultimate Edition.esp'
```

Shouldn't be an issue if the masterlist is correct.
