### ISSUE TITLE
Add Obsoleted messages to Mission Mojave Ultimate Edition'

### ISSUE THREAD

**Issue by ghost** [loot/falloutnv#65]
'[Mission Mojave Ultimate Edition](https://www.nexusmods.com/newvegas/mods/45104)' (which will henceforth be named MMUE for namesake) was a fix/tweak pack for New Vegas. The problem is that it made a lot of odd tweaks that were unnecessary and unrelated to it's mission of bugfixing, and worse, it has been unmaintained since 2015.

I'd suggest adding a "Superseded by [Yukinigai's Unofficial Patch](https://www.nexusmods.com/newvegas/mods/51664)" message to the MMUE plugins.

**Comment by MacSplody** [comment]
Okay, based on the chat in Discord.

```yaml
  - &updateToMMUE
    type: say
    content: 'Outdated. Consider using the latest version of Mission Mojave - Ultimate Edition instead.'
```

Should be replaced with
```yaml
  - &updateToYUP
    type: say
    content: 'Outdated. Consider using the latest version of Yukichigai Unofficial Patch - YUP instead.'
```

Which is currently applied to these plugins.
```yaml
OFT_Merge_All.esm
OFT_Merge_Base.esm
OFT_Merge_HonestHearts.esm
OFT_Merge_OldWorldBlues.esm
MM-Main.esp
MM-HonestHearts.esp
MM-OldWorldBlues.esp
MM-LonesomeRoad.esp
Community Bugfix Compilation Patch.esp
Compiled Patch All_DLCs.esp
```
