### ISSUE TITLE
A Thorny Situation Cleaning info

### ISSUE THREAD

**Issue by EssArrBee** [loot/falloutnv#7]
There was cleaning info listed for this mod, but it is not showing in the report.

From my meta data:

```
name: athornysituation.esp
tag:
  - Relations
  - Scripts
dirty:
  - crc: 0xcc32f754
    util: "[FNVEdit](http://www.nexusmods.com/newvegas/mods/34703)"
    itm: 10
```
