### ISSUE TITLE
FNVEdit Cleaning Reports

### ISSUE THREAD

**Issue by MacSplody** [loot/falloutnv#75]
Submit Quick Auto Cleaning Reports as a comment below.
Make sure you **link** the mod page and specify the mod **version** you cleaned as well.

[Quick Auto Clean](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#quickautoclean)
[Add arguments](https://user-images.githubusercontent.com/1944639/48548367-b2744b00-e8c4-11e8-8a75-a0b67a4d7ed8.png)
`-iknowwhatimdoing -quickautoclean` in MO2

If you're manually cleaning with expert mode, select [BOSS/LOOT Cleaning report](https://user-images.githubusercontent.com/1944639/63643744-5f3eec80-c6cf-11e9-95af-0b57c7e0940b.png) from the right click context menu.

[Copy the cleaning report](https://user-images.githubusercontent.com/1944639/48547682-1eee4a80-e8c3-11e8-8e2b-fd0b571f71fc.png)

It's preferable to wrap this in a code block comment for readability.
![image](https://user-images.githubusercontent.com/1944639/48547617-fb2b0480-e8c2-11e8-969d-f7b698b05e05.png)
![image](https://user-images.githubusercontent.com/1944639/63643765-03c12e80-c6d0-11e9-860e-ed3cd62f7222.png)

---

version: 1.4.0.525

```yaml
  - name: 'DeadMoney.esm'
    dirty:
      - <<: *quickClean
        crc: 0xD70F165B
        util: '[FNVEdit v4.0.0](https://www.nexusmods.com/newvegas/mods/34703)'
        itm: 403
        udr: 51
    clean:
      - crc: 0x6ACCD876
        util: 'FNVEdit v4.0.0'
```

**Comment by MacSplody** [comment]
[Weapons of the Wasteland - Weapon Distribution Tweaks and DLC Weapon Integration](https://www.nexusmods.com/newvegas/mods/66115)
version: 0.9b

```yaml
  - name: 'Weapons of the Wasteland.esm'
    clean:
      - crc: 0x4EA64653
        util: 'FNVEdit v4.0.2'
```

**Comment by pStyl3** [comment]
I've updated the cleaning info for all Official DLC.

Regarding Weapons of the Wasteland:
```yaml
  - name: 'Weapons of the Wasteland.esm'
    clean:
      - crc: 0x4EA64653
        util: 'FNVEdit v4.0.2f'
```
But also:
```
[00:00] Checking for Errors in [06] Weapons of the Wasteland.esm
[00:00] SHONVDLCFlakShrapWorkaround [SCPT:06014581]
[00:00]     SCPT -> Record marked as deleted but contains: Editor ID
[00:00] SHONVDLCWeaponModsExpandedScript [SCPT:0601BCE9]
[00:00]     SCPT -> Record marked as deleted but contains: Editor ID
[00:00] SHONVDLCDummyDoor [REFR:0600C21B] (places DoorStorefront01 "Door" [DOOR:000BEAFC] in GRUP Cell Persistent Children of SHONVDLCDummyCell "Goodsprings General Store" [CELL:06002BEB])
[00:00]     REFR \ XTEL - Teleport Destination \ Door -> Target is not persistent
[00:00] Done: Checking for Errors, Processed Records: 210, Errors found: 3, Elapsed Time: 00:00
```
