### ISSUE TITLE
A Wilder Wasteland cleaning info

### ISSUE THREAD

**Issue by EssArrBee** [loot/falloutnv#8]
from my metadata:

```
name: awilderwasteland.esp
inc:
  - name: awilderwastelandnobenny.esp
tag:
  - AI.Packages
  - Stats
dirty:
  - crc: 0xed3d7bb3
    util: "[FNVEdit](http://www.nexusmods.com/newvegas/mods/34703/?)"
    itm: 9
```
