### ISSUE TITLE
NewVegasBountiesII.esp (New Vegas Bounties II)

### ISSUE THREAD

**Issue by EssArrBee** [loot/falloutnv#9]
Cleaning info for latest version v1.47:

```
name: NewVegasBountiesII.esp
after:
  - name: NewVegasBounties.esp
tag:
  - Relations
dirty:
  - crc: 0x11d6afea
    util: *dirtyUtil
    nav: 2
```

Not sure what utility to put, but LOOT requires that field filled in.
